spring:
  application:
    name: demo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
logging:
  path: /logs/demo
  config: classpath:logback-boot.xml
  #日志存储地址
  file: "logs/config/demo-xx.log"
server:
  #端口号
  port: 8888
  #项目名，如果不设定，默认是 /
  #context-path: /
